version: '3'

volumes:
  django_sample_db_dev: {}

services:
  db:
    image: mariadb:10.4.18
    volumes:
      - django_sample_db_dev:/var/lib/mariadb/data
      - ./:/code
    environment:
      - MYSQL_DATABASE=catch
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=test00
      - MYSQL_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  djangoproject:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=db
      - DJANGO_DB_USERNAME=root
      - DJANGO_DB_PASSWORD=test00
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver 0:8000"
    volumes:
      - ./:/code
    depends_on:
      - db
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 10s
    #     max_attempts: 3
    #     window: 120s